In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'Nombre': ['Juan', 'Ana', 'Pedro'], 'Edad': [25, 30, 35]})
df1

In [ ]:
df2 = pd.DataFrame({'Nombre': ['Luis', 'Maria'], 'Edad': [28, 32]})

In [ ]:
df3 = pd.concat([df1, df2], axis=0, ignore_index=True)
df3

  Nombre  Edad
0   Juan    25
1    Ana    30
2  Pedro    35
3   Luis    28
4  Maria    32

In [ ]:

datos_cliente = pd.DataFrame({'Nombre': ["Ana", "Luis", "Marta"], 'Edad': [34, 45, 28]})
compras_cliente = pd.DataFrame({'Producto': ["Libro", "Lápiz", "Cuaderno"], 'Precio': [15.50, 0.50, 2.00]})

info_cliente = pd.concat([datos_cliente, compras_cliente], keys=['Datos del Cliente', 'Compras del Cliente'], axis=1)
info_cliente

  Nombre  Edad  Producto  Precio
0    Ana    34     Libro    15.5
1   Luis    45     Lápiz     0.5
2  Marta    28  Cuaderno     2.0